import Head from 'next/head'
import Panduanklaim from '../components/Panduanklaim'


export default function Pagepanduanklaim() {
return (
    <div>
    <Head>
        <title>ZechtAssurance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Panduanklaim/>
    </div>
)
}