import Head from 'next/head'
import Asuransipendidikan from '../components/Asuransipendidikan'


export default function Pageasuransipendidikan() {
return (
    <div>
    <Head>
        <title>ZechtAssurance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Asuransipendidikan/>
    </div>
)
}