import Head from 'next/head'
import Perlindunganbebaspremi from '../components/Perlindunganbebaspremi'



export default function Pageperlindunganbebaspremi() {
return (
    <div>
    <Head>
        <title>ZechtAssurance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Perlindunganbebaspremi/>
    </div>
)
}