import Head from 'next/head'
import Kebijakankami from '../components/Kebijakankami'



export default function Pagekebijakankami() {
return (
    <div>
    <Head>
        <title>ZechtAssurance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Kebijakankami/>
    </div>
)
}