import Head from 'next/head'
import Beritadanartikel from '../components/Beritadanartikel'



export default function Pageberita() {
return (
    <div>
    <Head>
        <title>ZechtAssurance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Beritadanartikel/>
    </div>
)
}