import Head from 'next/head'
import Jendelaberitadanartikel from '../components/Jendelaberitadanartikel'


export default function Pagejendelaberitadanartikel() {
return (
    <div>
    <Head>
        <title>ZechtAssurance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Jendelaberitadanartikel/>
    </div>
)
}