import Head from 'next/head'
import Hubungikami from '../components/Hubungikami'



export default function Pagehubungikami() {
return (
    <div>
    <Head>
        <title>ZechtAssurance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Hubungikami/>
    </div>
)
}