import Head from 'next/head'
import Mitrabisnis from '../components/Mitrabisnis'



export default function Pagemitrabisnis() {
return (
    <div>
    <Head>
        <title>ZechtAssurance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Mitrabisnis/>
    </div>
)
}