import Head from 'next/head'
import Tentangperusahaankami from '../components/Tentangperusahaankami'



export default function Pagetentangperusahaan() {
return (
    <div>
    <Head>
        <title>ZechtAssurance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Tentangperusahaankami/>
    </div>
)
}