import Head from 'next/head'
import Kebijakanprivasi from '../components/Kebijakanprivasi'



export default function Pagekebijakanprivasi() {
return (
    <div>
    <Head>
        <title>ZechtAssurance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Kebijakanprivasi/>
    </div>
)
}