import Head from 'next/head'
import Asuransikesehatan from '../components/Asuransikesehatan'




export default function Pageasuransikesehatan() {
return (
    <div>
    <Head>
        <title>ZechtAssurance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Asuransikesehatan/>
    </div>
)
}