import Head from 'next/head'
import Pembayaranpremi from '../components/Pembayaranpremi'


export default function Pagepembayaranpremi () {
  return (
    <div>
        <Head>
            <title>ZechtAssurance</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Pembayaranpremi/>
    </div>
  )
}