import Head from 'next/head'
import Asuransijiwa from '../components/Asuransijiwa'



export default function Pageasuransijiwa() {
return (
    <div>
    <Head>
        <title>ZechtAssurance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Asuransijiwa/>
    </div>
)
}