import Head from 'next/head'
import Tanggungjawabkami from '../components/Tanggungjawabkami'



export default function Pagetanggungjawab() {
return (
    <div>
    <Head>
        <title>ZechtAssurance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Tanggungjawabkami/>
    </div>
)
}